// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketManager.Models;

namespace TicketManager.Migrations
{
    [DbContext(typeof(ConcertDbContext))]
    [Migration("20210824070555_scaffold1")]
    partial class scaffold1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TicketManager.Models.Band", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nightwish"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dio"
                        },
                        new
                        {
                            Id = 3,
                            Name = "The Offspring"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Some classic singer"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Another singer"
                        });
                });

            modelBuilder.Entity("TicketManager.Models.Concert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BandId")
                        .HasColumnType("int");

                    b.Property<int>("ConcertTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BandId");

                    b.HasIndex("ConcertTypeId");

                    b.HasIndex("LocationId");

                    b.ToTable("Concerts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BandId = 1,
                            ConcertTypeId = 1,
                            Date = new DateTime(2021, 9, 24, 10, 5, 54, 905, DateTimeKind.Local).AddTicks(9900),
                            LocationId = 1
                        },
                        new
                        {
                            Id = 2,
                            BandId = 1,
                            ConcertTypeId = 1,
                            Date = new DateTime(2021, 10, 24, 10, 5, 54, 907, DateTimeKind.Local).AddTicks(7865),
                            LocationId = 2
                        },
                        new
                        {
                            Id = 3,
                            BandId = 2,
                            ConcertTypeId = 2,
                            Date = new DateTime(2021, 9, 24, 10, 5, 54, 907, DateTimeKind.Local).AddTicks(7929),
                            LocationId = 2
                        },
                        new
                        {
                            Id = 4,
                            BandId = 3,
                            ConcertTypeId = 3,
                            Date = new DateTime(2021, 11, 24, 10, 5, 54, 907, DateTimeKind.Local).AddTicks(7933),
                            LocationId = 1
                        });
                });

            modelBuilder.Entity("TicketManager.Models.ConcertType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameRu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConcertTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Classic music",
                            NameRu = "Классическая музыка"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Party",
                            NameRu = "Вечеринка"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Open Air",
                            NameRu = "Опенэйр"
                        });
                });

            modelBuilder.Entity("TicketManager.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameRu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 33.333300000000001,
                            Longitude = 44.444400000000002,
                            Name = "Unknown location"
                        },
                        new
                        {
                            Id = 2,
                            Latitude = 22.222200000000001,
                            Longitude = 55.555500000000002,
                            Name = "Another location"
                        });
                });

            modelBuilder.Entity("TicketManager.Models.PromoCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Coefficient")
                        .HasColumnType("float");

                    b.Property<int>("ConcertId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConcertId");

                    b.ToTable("PromoCodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "QWERTY",
                            Coefficient = 0.90000000000000002,
                            ConcertId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "PromoCode420",
                            Coefficient = 0.80000000000000004,
                            ConcertId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "SuperCode",
                            Coefficient = 0.75,
                            ConcertId = 2
                        },
                        new
                        {
                            Id = 4,
                            Code = "McCode",
                            Coefficient = 0.90000000000000002,
                            ConcertId = 3
                        });
                });

            modelBuilder.Entity("TicketManager.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConcertId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("bit");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ConcertId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcertId = 1,
                            CustomerInfo = " - ",
                            IsReserved = false,
                            Price = 5.0
                        },
                        new
                        {
                            Id = 2,
                            ConcertId = 1,
                            CustomerInfo = " - ",
                            IsReserved = false,
                            Price = 5.0
                        },
                        new
                        {
                            Id = 3,
                            ConcertId = 1,
                            CustomerInfo = " - ",
                            IsReserved = false,
                            Price = 5.0
                        },
                        new
                        {
                            Id = 4,
                            ConcertId = 2,
                            CustomerInfo = " - ",
                            IsReserved = false,
                            Price = 5.0
                        },
                        new
                        {
                            Id = 5,
                            ConcertId = 2,
                            CustomerInfo = " - ",
                            IsReserved = false,
                            Price = 5.0
                        },
                        new
                        {
                            Id = 6,
                            ConcertId = 2,
                            CustomerInfo = " - ",
                            IsReserved = false,
                            Price = 5.0
                        },
                        new
                        {
                            Id = 7,
                            ConcertId = 3,
                            CustomerInfo = " - ",
                            IsReserved = false,
                            Price = 5.0
                        },
                        new
                        {
                            Id = 8,
                            ConcertId = 3,
                            CustomerInfo = " - ",
                            IsReserved = false,
                            Price = 5.0
                        },
                        new
                        {
                            Id = 9,
                            ConcertId = 3,
                            CustomerInfo = " - ",
                            IsReserved = false,
                            Price = 5.0
                        },
                        new
                        {
                            Id = 10,
                            ConcertId = 4,
                            CustomerInfo = " - ",
                            IsReserved = false,
                            Price = 5.0
                        },
                        new
                        {
                            Id = 11,
                            ConcertId = 4,
                            CustomerInfo = " - ",
                            IsReserved = false,
                            Price = 5.0
                        },
                        new
                        {
                            Id = 12,
                            ConcertId = 4,
                            CustomerInfo = " - ",
                            IsReserved = false,
                            Price = 5.0
                        });
                });

            modelBuilder.Entity("TicketManager.Models.Concert", b =>
                {
                    b.HasOne("TicketManager.Models.Band", "Band")
                        .WithMany()
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketManager.Models.ConcertType", "ConcertType")
                        .WithMany()
                        .HasForeignKey("ConcertTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketManager.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("ConcertType");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("TicketManager.Models.PromoCode", b =>
                {
                    b.HasOne("TicketManager.Models.Concert", "Concert")
                        .WithMany("PromoCodes")
                        .HasForeignKey("ConcertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concert");
                });

            modelBuilder.Entity("TicketManager.Models.Ticket", b =>
                {
                    b.HasOne("TicketManager.Models.Concert", "Concert")
                        .WithMany("Tickets")
                        .HasForeignKey("ConcertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concert");
                });

            modelBuilder.Entity("TicketManager.Models.Concert", b =>
                {
                    b.Navigation("PromoCodes");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
